---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.14.1 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.14.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.14.1 includes new enhancements.

Additional features and enhancements are also introduced in the latest versions of the NetApp Console. See the https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html[Cloud Volumes ONTAP Release Notes^] for details.

== 9.14.1 P14 (16 October 2025)
The 9.14.1 P14 patch is now available for Cloud Volumes ONTAP for all cloud providers. The Console will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P14[View the list of bugs fixed in the P14 patch^] (NetApp Support Site login required).

== 9.14.1 P13 (04 July 2025)
The 9.14.1 P13 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P13[View the list of bugs fixed in the P13 patch^] (NetApp Support Site login required).

== 9.14.1 P12 (17 April 2025)
The 9.14.1 P12 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P12[View the list of bugs fixed in the P12 patch^] (NetApp Support Site login required).

== 9.14.1 P11 (10 March 2025)
The 9.14.1 P11 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P11[View the list of bugs fixed in the P11 patch^] (NetApp Support Site login required).

== 9.14.1 P10 (20 January 2025)
The 9.14.1 P10 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P10[View the list of bugs fixed in the P10 patch^] (NetApp Support Site login required).

== 9.14.1 P9 (25 November 2024)
The 9.14.1 P9 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P9[View the list of bugs fixed in the P9 patch^] (NetApp Support Site login required).

== 9.14.1 P8 (29 October 2024)
The 9.14.1 P8 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P8[View the list of bugs fixed in the P8 patch^] (NetApp Support Site login required).

== 9.14.1 P7 (29 August 2024)
The 9.14.1 P7 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P7[View the list of bugs fixed in the P7 patch^] (NetApp Support Site login required).

== 9.14.1 P6 (18 July 2024)
The 9.14.1 P6 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P6[View the list of bugs fixed in the P6 patch^] (NetApp Support Site login required).

== 9.14.1 P5 (03 July 2024)
The 9.14.1 P5 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P5[View the list of bugs fixed in the P5 patch^] (NetApp Support Site login required).

== 9.14.1 P4 (03 July 2024)
The 9.14.1 P4 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P4[View the list of bugs fixed in the P4 patch^] (NetApp Support Site login required).

== 9.14.1 P2 (18 April 2024)
The 9.14.1 P2 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P2[View the list of bugs fixed in the P2 patch^] (NetApp Support Site login required).

== 9.14.1 P1 (01 April 2024)
The 9.14.1 P1 patch is now available for Cloud Volumes ONTAP for all cloud providers. BlueXP will prompt you to upgrade your existing systems to this patch release.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.14.1P1[View the list of bugs fixed in the P1 patch^] (NetApp Support Site login required).

== 9.14.1 GA (05 March 2024)
Cloud Volumes ONTAP 9.14.1 General Availability release is now available in AWS, Azure, and Google Cloud. 

== 9.14.1 RC1 (06 December 2023)
The Release Candidate 1 of Cloud Volumes ONTAP 9.14.1 is now available in AWS, Azure, and Google Cloud. 

== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from BlueXP. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when BlueXP notifies you^].

=== Supported upgrade path

You can upgrade to Cloud Volumes ONTAP 9.14.1 from 9.13.1 and 9.14.0 releases. BlueXP will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

=== Required version of the Connector

The BlueXP Connector must be running version 3.9.27 or later to deploy new Cloud Volumes ONTAP 9.14.1 systems and to upgrade existing systems to 9.14.1.

TIP: Automatic upgrades of the Connector are enabled by default so you should be running the latest version.

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

=== c4, m4, and r4 instances no longer supported

In AWS, the c4, m4, and r4 EC2 instance types are no longer supported with Cloud Volumes ONTAP. If you have an existing system that's running on a c4, m4, or r4 instance type, you must change to an instance type in the c5, m5, or r5 instance family. You can't upgrade to this release until you change the instance type.
 
link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html[Learn how to change the EC2 instance type for Cloud Volumes ONTAP^].

Refer to link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html[NetApp Support^] to learn more about the end of availability and support for these instance types. 
